### ISSUE TITLE
feat: check ports on startup / .env file validation

### ISSUE THREAD

**Issue by safeina86** [d1onys1us-org/kittynode#123]
![Screenshot_2024-02-06_205716](https://github.com/d1onys1us/stn/assets/80200634/5b87bacf-666e-466e-9729-08a1c806fa94)

How can I fix this?

**Comment by d1onys1us** [comment]
@safeina86 what operating system is this?

**Comment by d1onys1us** [comment]
@safeina86 also can i have your rustc and cargo version? `rustc -V && cargo -V`

**Comment by d1onys1us** [comment]
@safeina86 can you try it again? i just pushed it a fix :)

**Comment by safeina86** [comment]
> @safeina86 what operating system is this?

ubuntu

**Comment by safeina86** [comment]
> @safeina86 also can i have your rustc and cargo version? `rustc -V && cargo -V`

rustc 1.72.1 (d5c2e9c34 2023-09-13) (built from a source tarball)
cargo 1.72.1

**Comment by safeina86** [comment]
> @safeina86 can you try it again? i just pushed it a fix :)

I will try again and let you know

**Comment by safeina86** [comment]
![Screenshot 2024-02-07 114725](https://github.com/d1onys1us/stn/assets/80200634/7577cce7-e91d-46f5-9630-0d1a3b2e00f6)
What does this line mean?

**Comment by safeina86** [comment]
How can I deal with this situation??

![Uploading Screenshot 2024-02-07 142233.png…]()

**Comment by safeina86** [comment]
How can I deal with this situation??
![Screenshot 2024-02-07 142233](https://github.com/d1onys1us/stn/assets/80200634/0564769b-9ffa-4809-b026-67d7db799aeb)

**Comment by d1onys1us** [comment]
> How can I deal with this situation?? ![Screenshot 2024-02-07 142233](https://private-user-images.githubusercontent.com/80200634/302977800-0564769b-9ffa-4809-b026-67d7db799aeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjMyNDUsIm5iZiI6MTcwNzMyMjk0NSwicGF0aCI6Ii84MDIwMDYzNC8zMDI5Nzc4MDAtMDU2NDc2OWItOWZmYS00ODA5LWIwMjYtNjdkN2RiNzk5YWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE2MjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0YWVjZTE1YWIyNDY2OGI3NTIyZDk2NDZlYWE1NGRmZWJhYzYzYjc4ZjAxOTI1NTM2NDZhNTU3YTMxZWZlNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u6J8FCEcmSsoRohgeG4YVWNgt_cbPTlHqWgT31z0cLQ)

are you already using port 8548 for something? you can check with `lsof -i tcp:8548`. it seems like that port is already being used. if you do have a process there, i would kill the pid with `kill <pid>` (insert pid from lsof command).

please let me know if this works. thx

**Comment by safeina86** [comment]
When nothing appears for me when I type lsof -i tcp:8548

There is a note that I would like to draw your attention to: I am running a Shardeum node on the same VPS but the Shardeum node is not running until I change port 3001 to 3002 from the .env file.

![Screenshot 2024-02-08 010004](https://github.com/d1onys1us/stn/assets/80200634/1a4c4a33-29cb-4639-b13a-46e7a9b59de5)

**Comment by safeina86** [comment]
![Screenshot 2024-02-08 011443](https://github.com/d1onys1us/stn/assets/80200634/fc084e87-e1ff-49dd-9ee2-5173c454bb5d)

**Comment by safeina86** [comment]
There is a note: - When I run the node from within stn, there is a conflict between the ports, but when I entered the .env file and I changed the ports, as shown in the attached image, and restarted the node from inside stn, the node ran without problems.

![Screenshot 2024-02-08 163059](https://github.com/d1onys1us/stn/assets/80200634/8c6925e3-fb0f-4cf2-b190-63be67fa06c9)

**Comment by safeina86** [comment]
@d1onys1us you here ??

**Comment by d1onys1us** [comment]
> @d1onys1us you here ??

Got it, sounds like I need to check for allocated ports before startup. Will do that to close this bug report, thank you.
