### ISSUE TITLE
Error "Diagnostic-width"

### ISSUE THREAD

**Issue by RylaiNode** [d1onys1us-org/kittynode#143]
Every time i paste `cargo install stn` to my vps it shows an error

_error: Unrecognized option: 'diagnostic-width'

error: could not compile `ff` (lib)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `stn v0.1.44`, intermediate artifacts can be found at `/tmp/cargo-installacWTl9`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path._

**Comment by d1onys1us** [comment]
@RylaiNode can you please share your operating system?

**Comment by safeina86** [comment]
@RylaiNode try this 

It looks like you are encountering an issue with the compilation of the "stn" crate using Cargo. The error message mentions an unrecognized option 'diagnostic-width', which might indicate a compatibility issue or a bug in the version of Rust or Cargo you are using.

Here are a few steps you can try to resolve the issue:

1. **Update Rust and Cargo:**
   Make sure you are using the latest stable version of Rust and Cargo. You can update them using the following commands:

   ```bash
   rustup update
   ```

2. **Clean Build:**
   Try cleaning the build artifacts and then reinstalling the package. Run the following commands:

   ```bash
   cargo clean
   cargo install stn
   ```

3. **Specify Version:**
   If updating doesn't solve the problem, you can try specifying a specific version of the "stn" crate. Use the following command to install a specific version:

   ```bash
   cargo install stn --version 0.1.43
   ```

   Replace '0.1.43' with the version you want to install.

4. **Check Dependencies:**
   Ensure that your VPS has all the necessary dependencies and build tools installed. Some Rust crates may require external dependencies to be present on the system.

   ```bash
   sudo apt-get install build-essential
   ```

   Install any other dependencies that the "stn" crate may require according to its documentation.

5. **Check Rust Edition:**
   Make sure that the Rust edition used by the project is compatible with the version of Rust you have installed. You can specify the edition in the `Cargo.toml` file:

   ```toml
   [package]
   edition = "2021"
   ```

Try these steps one by one and see if any of them resolve the issue. If the problem persists, you may want to check for any open issues in the "stn" repository on GitHub or seek help from the project's community for assistance.

**Comment by RylaiNode** [comment]
> @RylaiNode
> 
> It looks like you are encountering an issue with the compilation of the "stn" crate using Cargo. The error message mentions an unrecognized option 'diagnostic-width', which might indicate a compatibility issue or a bug in the version of Rust or Cargo you are using.
> 
> Here are a few steps you can try to resolve the issue:
> 
> 1. **Update Rust and Cargo:**
>    Make sure you are using the latest stable version of Rust and Cargo. You can update them using the following commands:
>    ```shell
>    rustup update
>    ```
> 2. **Clean Build:**
>    Try cleaning the build artifacts and then reinstalling the package. Run the following commands:
>    ```shell
>    cargo clean
>    cargo install stn
>    ```
> 3. **Specify Version:**
>    If updating doesn't solve the problem, you can try specifying a specific version of the "stn" crate. Use the following command to install a specific version:
>    ```shell
>    cargo install stn --version 0.1.43
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Replace '0.1.43' with the version you want to install.
> 4. **Check Dependencies:**
>    Ensure that your VPS has all the necessary dependencies and build tools installed. Some Rust crates may require external dependencies to be present on the system.
>    ```shell
>    sudo apt-get install build-essential
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Install any other dependencies that the "stn" crate may require according to its documentation.
> 5. **Check Rust Edition:**
>    Make sure that the Rust edition used by the project is compatible with the version of Rust you have installed. You can specify the edition in the `Cargo.toml` file:
>    ```toml
>    [package]
>    edition = "2021"
>    ```
> 
> Try these steps one by one and see if any of them resolve the issue.

thank you brother, it worked! Godbless you!
